version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
      - ./nginxconf/nginx.conf:/etc/nginx/nginx.conf

networks:
  default:
    external:
      name: proxy_network